# Generated by Django 4.2.19 on 2025-05-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_timeslot_timeconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeConfiguration",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
