# Generated by Django 4.2.19 on 2025-06-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_schedule"),
        ("mainapp", "0020_remove_time_models"),
    ]

    operations = []
